version: "3.7"
services:

  maozi-cloud-mysql:
    image: mysql:8.0.29
    container_name: maozi-cloud-mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
#      - ./maozi-cloud-mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ./maozi-cloud-mysql/data/mysql/:/var/lib/mysql/
    ports:
      - 3306:3306

  maozi-cloud-nacos:
    image: nacos/nacos-server:v2.0.4
    container_name: maozi-cloud-nacos
    env_file:
      - maozi-cloud-nacos/env/nacos-mysql.env
    ports:
      - 8848:8848
      - 9848:9848
      - 9555:9555
    restart: always

  maozi-cloud-redis:
    image: redis:6.2.6
    container_name: maozi-cloud-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./maozi-cloud-redis/config/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ./maozi-cloud-redis/data/redis/data:/data:rw
    command:
      /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf "

  maozi-cloud-basics-gateway:
    image: maozi-cloud-basics-gateway:laster
    container_name: maozi-cloud-basics-gateway
    restart: always
    ports:
      - 10000:10000
    environment:
      environment: test
      NACOS_CONFIG_SERVER: maozi-cloud-nacos:8848

  maozi-cloud-basics-monitor:
    image: maozi-cloud-basics-monitor:laster
    container_name: maozi-cloud-basics-monitor
    restart: always
    ports:
      - 8000:8000
    environment:
      environment: test
      NACOS_CONFIG_SERVER: maozi-cloud-nacos:8848


networks:
  default:
    external:
      name: maozi-cloud-network