spring:  
  boot: 
    admin: 
      discovery: 
        services: zhongshi-etc-*
      client:
        url: http://localhost:8000
        username: admin
        password: admin
        auto-deregistration: true
        instance: 
          prefer-ip: true
          metadata: 
            tags: 
              environment: 本地

endpoints:
  dubbo:
    enabled: true

management:
  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    dubbo:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-configs:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-references:
      enabled: true
    dubbo-properties:
      enabled: true
    health:
      show-details: ALWAYS