knife4j:
  enable: true
  # production: true
swagger:
  base-package: com.zhongshi.*.api
  title: "${spring.application.name}服务"
  description: ${spring.application.name}
  version: 1.0
  terms-of-service-url: www.zhongshi.com
  authorization:
    name: Authorization
    key-name: Authorization
    auth-regex: ^.*$
  contact:
    name: "中视信息科技"
    email: 1095071913@qq.com