spring: 
  datasource:
    select-datasource:
      jdbc-url: jdbc:mysql://${application-datasource-jdbc-url}?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${application-datasource-jdbc-username}
      password: ${application-datasource-jdbc-password}
      minimum-idle: 10
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP1
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1 
        
    update-datasource:
      jdbc-url: jdbc:mysql://${application-datasource-jdbc-url}?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${application-datasource-jdbc-username}
      password: ${application-datasource-jdbc-password}
      minimum-idle: 10
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP2
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1