spring:
  cloud:
    alibaba:
      seata:
        # 自定义事务组名称 tx_group，需要与服务端一致
        tx-service-group: tx-group

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: tx-group
  service:
   vgroup-mapping:
     tx-group: tx-group
  config:
    type: nacos
    nacos:
      namespace: public
      serverAddr: localhost:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: localhost:8848
      group : SEATA_GROUP
      namespace: public
      username: nacos
      password: nacos