project: 
  environment: ${environment:localhost}

server:
  port: ${application-port}
spring: 
  main:
    allow-bean-definition-overriding: true
  jackson: 
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

feign:
  okhttp: 
    enabled: true
  httpclient: 
    enabled: false
  sentinel: 
    enabled: true


logging: 
  test: OFF
  level: 
    root: ERROR
    com.zhongshi: INFO
    com.xxl.job.core.handler.impl.MethodJobHandler: INFO
    com.alibaba.nacos.client.config.impl.ClientWorker: ERROR
    com.alibaba.cloud.dubbo.service.DubboMetadataServiceInvocationHandler: OFF
    org.springframework.cloud.stream.binding.StreamListenerMessageHandler: INFO