spring: 
  cloud: 
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        # namespace: zhongshi-etc-test
      discovery:
        enabled: true
        register-enabled: true
        server-addr: 127.0.0.1:8848
        # namespace: zhongshi-etc-test