security:
  oauth2:
    client: 
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:1000/oauth/token
      user-authorization-uri: http://localhost:1000/oauth/authorize
    resource:
      token-info-uri: rpc
      user-info-uri: http://localhost:1000/user