application-port: 9090

application-project-name: gateway

spring: 
  cloud:
    sentinel:
      filter:
        enabled: false
      datasource:
        gw-flow:
          nacos:
            server-addr: ${spring.cloud.nacos.config.server-addr}
            dataId: ${spring.application.name}-gw-flow
            groupId: SENTINEL_GROUP
            rule-type: gw-flow
        gw-api-group:
          nacos:
            server-addr: ${spring.cloud.nacos.config.server-addr}
            dataId: ${spring.application.name}-gw-api-group
            groupId: SENTINEL_GROUP
            rule-type: gw-api-group
    gateway:
      discovery:
        locator:
          enabled: true


      default-filters:
      # - name: Hystrix
      #   args:
      #     name: default
      #     fallbackUri: forward:/gateway/fallback
      - StripPrefix=1
      - name: Retry
        args:
          retries: 1
          methods: GET,POST
          statuses: BAD_GATEWAY,GATEWAY_TIMEOUT,SERVICE_UNAVAILABLE
          series: INFORMATIONAL
          exceptions: java.net.ConnectException,org.springframework.cloud.gateway.support.NotFoundException


      routes: 
        - id: ZHONGSHI-ETC-USER
          uri: lb://zhongshi-etc-user
          predicates:
          - Path=/user/**
        
        - id: ZHONGSHI-ETC-OAUTH2
          uri: lb://zhongshi-etc-oauth2
          predicates:
          - Path=/oauth2/**

        - id: ZHONGSHI-ETC-USERS
          uri: lb://zhongshi-etc-users
          predicates:
          - Path=/users/**
          
        - id: ZHONGSHI-ETC-ORDER
          uri: lb://zhongshi-etc-order
          predicates:
          - Path=/order/**

        - id: ZHONGSHI-ETC-PAY
          uri: lb://zhongshi-etc-pay
          predicates:
          - Path=/pay/**
          
        - id: ZHONGSHI-ETC-SUPPLIER
          uri: lb://zhongshi-etc-supplier
          predicates:
          - Path=/supplier/**

        - id: ZHONGSHI-ETC-COPYWRITER
          uri: lb://zhongshi-etc-copywriter
          predicates:
          - Path=/copywriter/**
          
        - id: ZHONGSHI-ETC-ACTIVATION
          uri: lb://zhongshi-etc-activation
          predicates:
          - Path=/activation/**

        - id: ZHONGSHI-ETC-ALIYUN-COMMON
          uri: lb://zhongshi-etc-aliyun-common
          predicates:
          - Path=/aliyun/**
          
        - id: ZHONGSHI-ETC-BLACKLIST
          uri: lb://zhongshi-etc-blacklist
          predicates:
          - Path=/blacklist/**         
          
        - id: ZHONGSHI-ETC-REDIS
          uri: lb://zhongshi-etc-redis
          predicates:
          - Path=/redis/**
          
        - id: ZHONGSHI-ETC-TRC
          uri: lb://zhongshi-etc-trc
          predicates:
          - Path=/trc/** 

        - id: ZHONGSHI-ETC-REFUND
          uri: lb://zhongshi-etc-refund
          predicates:
          - Path=/refund/**          

        - id: ZHONGSHI-ETC-LUWANGUSERS
          uri: lb://zhongshi-etc-luwangusers
          predicates:
          - Path=/luwangusers/**   

        - id: ZHONGSHI-ETC-SSO
          uri: lb://zhongshi-etc-sso
          predicates:
          - Path=/sso/**
                  
        - id: ZHONGSHI-ETC-STOREUSERS
          uri: lb://zhongshi-etc-storeusers
          predicates:
          - Path=/storeusers/**

        - id: ZHONGSHI-ETC-REFUND
          uri: lb://zhongshi-etc-refund
          predicates:
          - Path=/refund/**

        - id: ZHONGSHI-ETC-SUPPORTSERV
          uri: lb://zhongshi-etc-supportserv
          predicates:
          - Path=/supportserv/**

        - id: ZHONGSHI-ETC-ASSEMBLELOG
          uri: lb://zhongshi-etc-assemblelog
          predicates:
          - Path=/assemblelog/**

        - id: ZHONGSHI-ETC-AFTERSALE
          uri: lb://zhongshi-etc-aftersale
          predicates:
          - Path=/aftersale/**
         
        - id: ZHONGSHI-ETC-MESSAGE
          uri: lb://zhongshi-etc-message
          predicates:
          - Path=/message/**

        - id: ZHONGSHI-ETC-PARTNERDATASYNC
          uri: lb://zhongshi-etc-partnerdatasync
          predicates:
          - Path=/partnerdatasync/**
          #filters:
          #- StripPrefix=1
          #- SwaggerHeaderFilter


# hystrix:
#   enabled: true
#   shareSecurityContext: true
#   command:
#     default:
#       execution:
#         isolation:
#           strategy: SEMAPHORE
#           thread:
#             timeoutInMilliseconds: 3000


      # default-filters:
      #   - name: Hystrix
      #     args:
      #       name: default
      #       #转发地址
      #       fallbackUri: 'forward:/fallback'
      #   - name: Retry
      #     args:
      #       #重试次数，默认值是 3 次
      #       retries: 3
      #       #HTTP 的状态返回码
      #       statuses: BAD_GATEWAY,BAD_REQUEST
      #       #指定哪些方法的请求需要进行重试逻辑，默认值是 GET 方法
      #       methods: GET,POST