application-port: 60000

application-project-name: user-mq-consume



spring:
  cloud:
    stream:
      rocketmq: 
        bindings:
          zhongshi-log-topic: {consumer.orderly: true}
      bindings: { 

        zhongshi-log-topic: {
          destination: zhongshi-log-topic, 
          content-type: text/plain, 
          group: zhongshi-log-group,
          consumer.maxAttempts: 3,
          }

         }
  

        


