version: '3.1'
services:
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.3.0
    restart: always
    container_name: xxl-job-admin
    environment:
      PARAMS: "--spring.datasource.url=jdbc:mysql://rm-wz9dllf3590kpcran7o.mysql.rds.aliyuncs.com:3306/xxl_job_test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=jiumao --spring.datasource.password=Jiumao2022^&*"
      TZ: Asia/Shanghai
    volumes:
      - /usr/local/docker/xxl-job/data:/data/applogs
    ports:
      - 12000:8080
